### ISSUE TITLE
Uncovered lines are placed at the end of a function

### ISSUE THREAD

**Issue by bmwalters** [twittemb/XcodeCoverageConverter#6]
## Problem
If a function is 4 lines long and has 50% line coverage, then the Cobertura and Sonarqube reports generated by `xcc` will report lines 1 and 2 as covered and lines 3 and 4 as uncovered, regardless of the actual line coverage data present in the `xcresult` file. I assume this is because `xccov view --report` does not output detailed line coverage information on its own.

## Possible Solutions
`xccov view --archive --file /Users/foo/projects/bar/hi.swift ./foo.xcresult` provides per-line coverage information. There is no `--json` option to this subcommand, but its output format is documented in the `xccov` man page so it should be stable to parse (see [xccov-to-sonarqube-generic.sh](https://github.com/SonarSource/sonar-scanning-examples/blob/881455c1f79ed0282d3726247df7998f2105a801/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh) for an example). One big problem is that invoking `xccov` once per file is quite [slow](https://github.com/SonarSource/sonar-scanning-examples/issues/68), on the order of hundreds of ms per file.

Unfortunately I think xccov is the only documented stable interface into xcresult coverage data (xccovreport and xccovarchive files), so any solution probably has to work within its interface.

Perhaps a solution could take advantage of either `xccov diff --json ./before.xcresult ./after.xcresult` or version control information to only run the expensive `xccov view --archive --file` command on files which have changed since some previous report?

**Comment by softreigns** [comment]
going xcov route almost triple the test time, so totally discarded that solution and build a xslt convertor on top of the cobertura xml to get the sonar generic report.

https://github.com/softreigns/coverage-report-cobertura-to-sonar-generic

**Comment by fadookie** [comment]
This is a huge problem, the output from this tool is misleading and inaccurate. It creates a sense of false precision around information lost in the xccov json report.

I am investigating using https://github.com/a7ex/xcresultparser instead, which does take the time to convert line coverage by calling `xccov view --archive --file` for several files in parallel. It's a bit slow, but it works, and as far as I can tell this is the only way to get line coverage out of an xcresult bundle. Unfortunately it only supports sonarqube and not cobertura, but I will work on adding cobertura support.

**Comment by fadookie** [comment]
I have completed work on integrating a Cobertura output format into xcresultparser which will hopefully be merged soon: https://github.com/a7ex/xcresultparser/pull/7

This uses some code from XcodeCoverageConverter under the terms of the MIT license. I'm afraid there's not a good solution for this problem otherwise due to the limitations of the xccov json report format. At this point it may be easier to just add new output formats to xcresultparser which actually can parse line-level coverage.

**Comment by fadookie** [comment]
My PR is merged and cobertura XML support is now available in [the latest release of xcresultparser](https://github.com/a7ex/xcresultparser/releases/tag/1.2.0) on homebrew. If people want to generate line coverage reports from an xcresult bundle, my recommendation going forward is to add support for the desired coverage report format into xcresultparser, as the content pipeline for XcodeCoverageConverter is really not usable for line coverage reports, and we probably don't need two of these tools.

I would like to express my thanks to the developers of XcodeCoverageConverter for releasing their tool under the MIT license, which allowed me to re-purpose some code from the Cobertura exporter for xcc which made it a lot easier to get this format supported in xcuresultparser. This is what's beautiful about open source, bits of code can remain useful as requirements change and can be picked up by new developers.

**Comment by twittemb** [comment]
Thanks for sharing your work. I can close the issue I guess.
